{
 "title": "Expense",
 "time": { "from": "2025-06-10T05:57:11.490Z", "to": "2025-06-10T06:38:32.852Z" },
 "panels": [
  {
   "title": "System Status check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ec2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Services Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\",state=\"active\"}",
     "legendFormat": "{{exported_name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"backend.service\",state=\"active\"}",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "CPU Used %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance) ((1-(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "(1-((node_memory_MemFree_bytes+ node_memory_Buffers_bytes+node_memory_Cached_bytes)/ node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Queue/Drop Down",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_ethtool_pps_allowance_exceeded[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}