format_version: 10

pipelines:
  jenkins:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/teju-devopss/miscellaneous-code
        branch: main

    stages:
      - apply:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments: [ "ansible.sh","elasticsearch"]

