format_version: 10
pipelines:
  miscellaneous-terraform-destroy:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/teju-devopss/miscellaneous-code
        shallow_clone: false
        auto_update: true
        branch: main
        includes:
          - src/**/*.*
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              approval:
                type: manual
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments: ["delete-alb.sh"]
