- name: Copy Jenkins Repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
      - jenkins
    state: installed

- name: Start Jenkins Service
  ansible.builtin.systemd_service:
    name: jenkins
    state: started
    enabled: yes

- name: Install python3 and python3-jenkins on the target
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install python-jenkins using pip
  pip:
    name: python-jenkins
    executable: pip3

- name: Create Job
  community.general.jenkins_job:
     config: "{{ lookup('template', 'templates/pipeline.xml') }}"
     name: "{{item}}"
     password: admin123
     url: http://jenkins-int.tejudevops.online:8080
     user: admin
  loop:
     - frontend
     - catalogue
     - cart
     - user
     - payment
     - shipping
     - dispatch




