- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Java and Jenkins
  yum:
    name:
      - fontconfig
      - java-21-openjdk
      - jenkins
    state: present

- name: Enable Jenkins service
  systemd:
    name: jenkins
    enabled: yes
    daemon_reload: yes

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline.xml') }}"
    name: {{item}}
    password: admin
    url: http://jenkins-int.tejudevops.online:8080
    user: admin
  loop:
    - frontend